var examples =
[
    [ "arc_demo.c", "arc_demo_8c-example.html", null ],
    [ "attach.c", "attach_8c-example.html", null ],
    [ "character_map.c", "character_map_8c-example.html", null ],
    [ "chfont_demo.c", "chfont_demo_8c-example.html", null ],
    [ "encoding_list.c", "encoding_list_8c-example.html", null ],
    [ "encryption.c", "encryption_8c-example.html", null ],
    [ "ext_gstate_demo.c", "ext_gstate_demo_8c-example.html", null ],
    [ "font_demo.c", "font_demo_8c-example.html", null ],
    [ "grid_demo.c", "grid_demo_8c-example.html", null ],
    [ "grid_sheet.c", "grid_sheet_8c-example.html", null ],
    [ "handler.c", "handler_8c-example.html", null ],
    [ "image_demo.c", "image_demo_8c-example.html", null ],
    [ "jpeg_demo.c", "jpeg_demo_8c-example.html", null ],
    [ "jpfont_demo.c", "jpfont_demo_8c-example.html", null ],
    [ "line_demo.c", "line_demo_8c-example.html", null ],
    [ "link_annotation.c", "link_annotation_8c-example.html", null ],
    [ "make_rawimage.c", "make_rawimage_8c-example.html", null ],
    [ "minimal.c", "minimal_8c-example.html", null ],
    [ "outline_demo.c", "outline_demo_8c-example.html", null ],
    [ "outline_demo_jp.c", "outline_demo_jp_8c-example.html", null ],
    [ "permission.c", "permission_8c-example.html", null ],
    [ "png_demo.c", "png_demo_8c-example.html", null ],
    [ "raw_image_demo.c", "raw_image_demo_8c-example.html", null ],
    [ "slide_show_demo.c", "slide_show_demo_8c-example.html", null ],
    [ "text_annotation.c", "text_annotation_8c-example.html", null ],
    [ "text_demo2.c", "text_demo2_8c-example.html", null ],
    [ "text_demo.c", "text_demo_8c-example.html", null ],
    [ "ttfont_demo.c", "ttfont_demo_8c-example.html", null ],
    [ "ttfont_demo_jp.c", "ttfont_demo_jp_8c-example.html", null ]
];