var files_dup =
[
    [ "hpdf.h", "hpdf_8h.html", "hpdf_8h" ],
    [ "hpdf_3dmeasure.h", "hpdf__3dmeasure_8h.html", "hpdf__3dmeasure_8h" ],
    [ "hpdf_annotation.h", "hpdf__annotation_8h.html", "hpdf__annotation_8h" ],
    [ "hpdf_catalog.h", "hpdf__catalog_8h.html", "hpdf__catalog_8h" ],
    [ "hpdf_conf.h", "hpdf__conf_8h.html", "hpdf__conf_8h" ],
    [ "hpdf_consts.h", "hpdf__consts_8h.html", "hpdf__consts_8h" ],
    [ "hpdf_destination.h", "hpdf__destination_8h.html", "hpdf__destination_8h" ],
    [ "hpdf_doc.h", "hpdf__doc_8h.html", "hpdf__doc_8h" ],
    [ "hpdf_encoder.h", "hpdf__encoder_8h.html", "hpdf__encoder_8h" ],
    [ "hpdf_encrypt.h", "hpdf__encrypt_8h.html", "hpdf__encrypt_8h" ],
    [ "hpdf_encryptdict.h", "hpdf__encryptdict_8h.html", "hpdf__encryptdict_8h" ],
    [ "hpdf_error.h", "hpdf__error_8h.html", "hpdf__error_8h" ],
    [ "hpdf_exdata.h", "hpdf__exdata_8h.html", "hpdf__exdata_8h" ],
    [ "hpdf_ext_gstate.h", "hpdf__ext__gstate_8h.html", "hpdf__ext__gstate_8h" ],
    [ "hpdf_font.h", "hpdf__font_8h.html", "hpdf__font_8h" ],
    [ "hpdf_fontdef.h", "hpdf__fontdef_8h.html", "hpdf__fontdef_8h" ],
    [ "hpdf_gstate.h", "hpdf__gstate_8h.html", "hpdf__gstate_8h" ],
    [ "hpdf_image.h", "hpdf__image_8h.html", "hpdf__image_8h" ],
    [ "hpdf_info.h", "hpdf__info_8h.html", "hpdf__info_8h" ],
    [ "hpdf_list.h", "hpdf__list_8h.html", "hpdf__list_8h" ],
    [ "hpdf_mmgr.h", "hpdf__mmgr_8h.html", "hpdf__mmgr_8h" ],
    [ "hpdf_namedict.h", "hpdf__namedict_8h.html", "hpdf__namedict_8h" ],
    [ "hpdf_objects.h", "hpdf__objects_8h.html", "hpdf__objects_8h" ],
    [ "hpdf_outline.h", "hpdf__outline_8h.html", "hpdf__outline_8h" ],
    [ "hpdf_page_label.h", "hpdf__page__label_8h.html", "hpdf__page__label_8h" ],
    [ "hpdf_pages.h", "hpdf__pages_8h.html", "hpdf__pages_8h" ],
    [ "hpdf_pdfa.h", "hpdf__pdfa_8h.html", "hpdf__pdfa_8h" ],
    [ "hpdf_streams.h", "hpdf__streams_8h.html", "hpdf__streams_8h" ],
    [ "hpdf_types.h", "hpdf__types_8h.html", "hpdf__types_8h" ],
    [ "hpdf_u3d.h", "hpdf__u3d_8h.html", "hpdf__u3d_8h" ],
    [ "hpdf_utils.h", "hpdf__utils_8h.html", "hpdf__utils_8h" ],
    [ "hpdf_version.h", "hpdf__version_8h.html", "hpdf__version_8h" ]
];